name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: cmake --build . --config Release --parallel
    - name: run tests
      run: |
        ./tests/tests '~[long_run]'
        ./tests/tests '[long_run]'
