name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      BINARY_NAME: msync-$GITHUB_REF-osx-catalina-x64

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      run: cd build; cmake --build . --config Release --parallel
    - name: run tests
      run: |
        cd build
        ./tests/tests '~[long_run]'
        ./tests/tests '[long_run]'
    - name: Grab built executable
      run: mv build/msync $BINARY_NAME; ls
